### ISSUE TITLE
D-Series Support

### ISSUE THREAD

**Issue by davidcrossland** [azurecoder/fluent-management#43]
When i attempt to create a vm/cluster using STANDARD_D1 vmSize i get the following error

A first chance exception of type 'Elastacloud.AzureManagement.Fluent.Types.Exceptions.FluentManagementWebException' occurred in Elastacloud.AzureManagement.Fluent.dll
iisexpress.exe Information: 0 : ClusterId 11073: Operational Message: (100, "Failed to create VM from gallery.") (Persistant)
iisexpress.exe Error: 0 : ClusterId 11073: The 'Create Cluster' process failed to complete with error (4, "Failed to create VM from gallery.") and exception Some
  Elastacloud.AzureManagement.Fluent.Types.Exceptions.FluentManagementWebException: <Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Code>BadRequest</Code><Message>Value 'STANDARD_D1' specified for parameter 'RoleSize' is invalid. Allowed values are 'ExtraSmall,Small,Medium,Large,ExtraLarge,A5,A6,A7,A8,A9,A10,A11,Basic_A0,Basic_A1,Basic_A2,Basic_A3,Basic_A4,Standard_D1,Standard_D2,Standard_D3,Standard_D4,Standard_D11,Standard_D12,Standard_D13,Standard_D14,Standard_DS1,Standard_DS2,Standard_DS3,Standard_DS4,Standard_DS11,Standard_DS12,Standard_DS13,Standard_DS14,Standard_G1,Standard_G2,Standard_G3,Standard_G4,Standard_G5'.</Message></Error>
   at Elastacloud.AzureManagement.Fluent.Commands.Services.ServiceCommand.Execute()
   at Elastacloud.AzureManagement.Fluent.Clients.LinuxVirtualMachineClient.CreateNewVirtualMachineDeploymentFromTemplateGallery(List`1 properties, String cloudServiceName, ServiceCertificateModel serviceCertificate, String location, String affinityGroup)
   at Elastacloud.Brisk.ClusterManager.Provisioning.ClusterCommands.createIaasCluster@195-14.Invoke(Unit unitVar0) in C:\Users\david\Work\elastacloud\brisk\clustermanager-v2\src\ClusterManager\Provisioning\ClusterCommands.fs:line 195
   at Elastacloud.Brisk.ResultHelper.guardWith[a](Int32 error_0, String error_1, FSharpFunc`2 code) in C:\Users\david\Work\elastacloud\brisk\clustermanager-v2\src\DataAccess\SharedTypes.fs:line 94.
iisexpress.exe Information: 0 : ClusterId 11073: State is now Failed (Persistant).

**Comment by azurecoder** [comment]
Casing issue -tested and fixed
